///////////////////////////////////////////////////////////////////////////////
//
//      Project:  Aurora Module Generator version 2.8
//
//         Date:  $Date: 2007/09/28 12:50:35 $
//          Tag:  $Name: i+HEAD+134158 $
//         File:  $RCSfile: gtp_wrapper.ejava,v $
//          Rev:  $Revision: 1.2 $
//
//      Company:  Xilinx
//
//   Disclaimer:  XILINX IS PROVIDING THIS DESIGN, CODE, OR
//                INFORMATION "AS IS" SOLELY FOR USE IN DEVELOPING
//                PROGRAMS AND SOLUTIONS FOR XILINX DEVICES.  BY
//                PROVIDING THIS DESIGN, CODE, OR INFORMATION AS
//                ONE POSSIBLE IMPLEMENTATION OF THIS FEATURE,
//                APPLICATION OR STANDARD, XILINX IS MAKING NO
//                REPRESENTATION THAT THIS IMPLEMENTATION IS FREE
//                FROM ANY CLAIMS OF INFRINGEMENT, AND YOU ARE
//                RESPONSIBLE FOR OBTAINING ANY RIGHTS YOU MAY
//                REQUIRE FOR YOUR IMPLEMENTATION.  XILINX
//                EXPRESSLY DISCLAIMS ANY WARRANTY WHATSOEVER WITH
//                RESPECT TO THE ADEQUACY OF THE IMPLEMENTATION,
//                INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OR
//                REPRESENTATIONS THAT THIS IMPLEMENTATION IS FREE
//                FROM CLAIMS OF INFRINGEMENT, IMPLIED WARRANTIES
//                OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
//                PURPOSE.
//
//                (c) Copyright 2004 Xilinx, Inc.
//                All rights reserved.
//

////////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   / 
// /___/  \  /    Vendor: Xilinx 
// \   \   \/     Version : 7.1i
//  \   \         Application : 
//  /   /         Filename : GTP_WRAPPER.v
// /___/   /\     Timestamp : 02/08/2005 09:12:43
// \   \  /  \ 
//  \___\/\___\ 
//
//Command: 
//Design Name: GTP_WRAPPER
//
// Module GTP_WRAPPER
// Generated by Xilinx Architecture Wizard
// Written for synthesis tool: XST
`timescale 1ns / 1ps

module aurora_201_GTP_WRAPPER #
(
    // Simulation attributes
    parameter   SIM_GTPRESET_SPEEDUP=   0,      // Set to 1 to speed up sim reset
    parameter   SIM_PLL_PERDIV2     =   9'h14d,    // Set to the VCO Unit Interval time
    // Channel bond MASTER/SLAVE connection
    parameter CHAN_BOND_MODE_0      = "OFF",
    parameter CHAN_BOND_MODE_1      = "OFF",
    // Refclk attributes
    parameter   CLKINDC_B           =   "TRUE"
)

(

//---------------------- Loopback and Powerdown Ports ----------------------
   LOOPBACK_IN,
//--------------------- Receive Ports - 8b10b Decoder ----------------------
    RXCHARISCOMMA_OUT,
    RXCHARISK_OUT,
    RXDISPERR_OUT,
    RXNOTINTABLE_OUT,
//----------------- Receive Ports - Channel Bonding Ports -----------------
    ENCHANSYNC_IN,
    CHBONDDONE_OUT,
//----------------- Receive Ports - Clock Correction Ports -----------------
    RXBUFERR_OUT,
//------------- Receive Ports - Comma Detection and Alignment --------------
    RXREALIGN_OUT,
    ENMCOMMAALIGN_IN,
    ENPCOMMAALIGN_IN,
//----------------- Receive Ports - RX Data Path interface -----------------
    RXDATA_OUT,
    RXRECCLK1_OUT,
    RXRECCLK2_OUT,
    RXRESET_IN,
    RXUSRCLK_IN,
    RXUSRCLK2_IN,
//----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    RX1N_IN,
    RX1P_IN,
//--------------- Receive Ports - RX Polarity Control Ports ----------------
    RXPOLARITY_IN,
//------------------- Shared Ports - Tile and PLL Ports --------------------
    REFCLK,
    GTPRESET_IN,
    PLLLKDET_OUT,
    POWERDOWN_IN,
//-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
    TXCHARISK_IN,
//---------------- Transmit Ports - TX Data Path interface -----------------
    TXDATA_IN,
    TXOUTCLK1_OUT,
    TXOUTCLK2_OUT,
    TXRESET_IN,
    TXUSRCLK_IN,
    TXUSRCLK2_IN,
    TXBUFERR_OUT,
//------------- Transmit Ports - TX Driver and OOB signalling --------------
    TX1N_OUT,
    TX1P_OUT
);
//***************************** Port Declarations *****************************
//---------------------- Loopback and Powerdown Ports ----------------------
 input    [2:0]    LOOPBACK_IN;
//--------------------- Receive Ports - 8b10b Decoder ----------------------
 
 output   [1:0]    RXCHARISCOMMA_OUT; 
 output   [1:0]    RXCHARISK_OUT; 
 output   [1:0]    RXDISPERR_OUT;
 output   [1:0]    RXNOTINTABLE_OUT;
//----------------- Receive Ports - Channel Bonding Ports -----------------
 
 input             ENCHANSYNC_IN; 
 output            CHBONDDONE_OUT;
//----------------- Receive Ports - Clock Correction Ports -----------------
 output            RXBUFERR_OUT;
//------------- Receive Ports - Comma Detection and Alignment --------------
 output            RXREALIGN_OUT;
 input             ENMCOMMAALIGN_IN;
 input             ENPCOMMAALIGN_IN;
//----------------- Receive Ports - RX Data Path interface -----------------
 output   [15:0]   RXDATA_OUT; 
 output            RXRECCLK1_OUT;
 output            RXRECCLK2_OUT;
 input             RXRESET_IN;
  input             RXUSRCLK_IN;
 input             RXUSRCLK2_IN;
//----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
 
 input             RX1N_IN;  
 input             RX1P_IN;  
//--------------- Receive Ports - RX Polarity Control Ports ----------------
 input             RXPOLARITY_IN;
//------------------- Shared Ports - Tile and PLL Ports --------------------
 input             REFCLK;
 input             GTPRESET_IN;
 output            PLLLKDET_OUT;
 input             POWERDOWN_IN;
//-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
 input    [1:0]    TXCHARISK_IN; 
//---------------- Transmit Ports - TX Data Path interface -----------------
 input    [15:0]   TXDATA_IN; 
 output            TXOUTCLK1_OUT;
 output            TXOUTCLK2_OUT;
 input             TXRESET_IN;
 output            TXBUFERR_OUT;
 input             TXUSRCLK_IN;
 input             TXUSRCLK2_IN;
//------------- Transmit Ports - TX Driver and OOB signalling --------------
 output            TX1N_OUT;
 output            TX1P_OUT;

//***************************** Wire Declarations *****************************
// Ground and VCC signals
 wire               tied_to_ground_i;
 wire    [63:0]     tied_to_ground_vec_i;
 wire               tied_to_vcc_i;
 wire    [63:0]     tied_to_vcc_vec_i;
// floating input port connection signals
 wire     [1:0]    open_rxbufstatus_i;
 wire              open_txbufstatus_i;
// wire to output lock signal
 wire              plllkdet_i;
// Electrical idle reset logic signals
 wire               rxenelecidleresetb_i;
 wire               rxelecidle0_i;
 wire               resetdone0_i;
 wire               rxelecidlereset0_i;
 wire               rxelecidle1_i;
 wire               resetdone1_i;
 wire               rxelecidlereset1_i;

// Channel Bonding 3
 wire     [2:0]    chbondi;
 wire     [2:0]    chbondo;
   
 wire     [2:0]    chbondi_unused_i;
 wire              serialloopback_i;

//***************************** Register Declarations *****************************
// All TX inputs registered

//********************************* Main Body of Code**************************
//-------------------------  Static signal Assigments ---------------------   
 assign tied_to_ground_i             = 1'b0;
 assign tied_to_ground_vec_i         = 64'h0000000000000000;
 assign tied_to_vcc_i                = 1'b1;
 assign tied_to_vcc_vec_i            = 64'hffffffffffffffff;

 
// Assign lock signals
 assign  PLLLKDET_OUT  =   plllkdet_i;


 assign serialloopback_i   = !LOOPBACK_IN[0] && LOOPBACK_IN[1] && !LOOPBACK_IN[2];

//-------------------------  Electrical Idle Reset Circuit  ---------------
//Drive RXELECIDLERESET with elec idle reset enabled during normal operation when RXELECIDLE goes high
 assign  rxelecidlereset0_i = (rxelecidle0_i && resetdone0_i) && !serialloopback_i;
 assign  rxelecidlereset1_i = (rxelecidle1_i && resetdone1_i) && !serialloopback_i;
 assign  rxenelecidleresetb_i = !(rxelecidlereset0_i||rxelecidlereset1_i); 

// Channel Bonding
 assign chbondi_unused_i  = 3'b000;
 assign  chbondi = chbondi_unused_i;

//------------------------- GTP Instantiations  --------------------------   
 

//*************************************************************************************************            
//-----------------------------------ODD GTP------------------------------------------------
//*************************************************************************************************
GTP_DUAL # 
    (
        //_______________________ Simulation-Only Attributes __________________
         .SIM_GTPRESET_SPEEDUP         (SIM_GTPRESET_SPEEDUP),
         .SIM_PLL_PERDIV2              (SIM_PLL_PERDIV2),

         //___________________________ Shared Attributes _______________________
         //---------------------- Tile and PLL Attributes ----------------------
         .CLK25_DIVIDER               (6), 
         .CLKINDC_B                   (CLKINDC_B),   
         .OOB_CLK_DIVIDER             (6),
         .OVERSAMPLE_MODE             ("FALSE"),
         .PLL_DIVSEL_FB               (2),
         .PLL_DIVSEL_REF              (1),
         .PLL_TXDIVSEL_COMM_OUT       (1),
         .TX_SYNC_FILTERB             (1),

         //______________________ Transmit Interface Attributes ________________
         //----------------- TX Buffering and Phase Alignment ------------------   
         .TX_BUFFER_USE_0            ("TRUE"),
         .TX_XCLK_SEL_0              ("TXOUT"),
         .TXRX_INVERT_0              (5'b00000),        
         .TX_BUFFER_USE_1            ("TRUE"),
         .TX_XCLK_SEL_1              ("TXOUT"),
         .TXRX_INVERT_1              (5'b00000),        

         //------------------- TX Serial Line Rate settings --------------------   
         .PLL_TXDIVSEL_OUT_0         (2),
         .PLL_TXDIVSEL_OUT_1         (2), 

         //------------------- TX Driver and OOB signalling --------------------  
         .TX_DIFF_BOOST_0           ("TRUE"),
         .TX_DIFF_BOOST_1           ("TRUE"),

         //---------------- TX Pipe Control for PCI Express/SATA ---------------
         .COM_BURST_VAL_0            (4'b1111),
         .COM_BURST_VAL_1            (4'b1111),

         //_______________________ Receive Interface Attributes ________________
         //---------- RX Driver,OOB signalling,Coupling and Eq.,CDR ------------  
         .AC_CAP_DIS_0               ("TRUE"),
         .OOBDETECT_THRESHOLD_0      (3'b001),
         .PMA_CDR_SCAN_0             (27'h6C08040), 
         .PMA_RX_CFG_0               (25'h0DCE089),
         .RCV_TERM_GND_0             ("FALSE"),
         .RCV_TERM_MID_0             ("FALSE"),
         .RCV_TERM_VTTRX_0           ("TRUE"),
         .TERMINATION_IMP_0          (50),
         .AC_CAP_DIS_1               ("TRUE"),
         .OOBDETECT_THRESHOLD_1      (3'b001),
         .PMA_CDR_SCAN_1             (27'h6C08040), 
         .PMA_RX_CFG_1               (25'h0DCE089),  
         .RCV_TERM_GND_1             ("FALSE"),
         .RCV_TERM_MID_1             ("FALSE"),
         .RCV_TERM_VTTRX_1           ("TRUE"),
         .TERMINATION_IMP_1          (50),
         .TERMINATION_CTRL           (5'b10100),
         .TERMINATION_OVRD           ("FALSE"),

         //------------------- RX Serial Line Rate Settings --------------------   
         .PLL_RXDIVSEL_OUT_0         (2),
         .PLL_SATA_0                 ("FALSE"),
         .PLL_RXDIVSEL_OUT_1         (2),
         .PLL_SATA_1                 ("FALSE"),

         //------------------------- PRBS Detection ----------------------------  
         .PRBS_ERR_THRESHOLD_0       (32'h00000008),
         .PRBS_ERR_THRESHOLD_1       (32'h00000008),

         //------------------- Comma Detection and Alignment -------------------  
         .ALIGN_COMMA_WORD_0         (2),
         .COMMA_10B_ENABLE_0         (10'b1111111111),
         .COMMA_DOUBLE_0             ("FALSE"),
         .DEC_MCOMMA_DETECT_0        ("TRUE"),
         .DEC_PCOMMA_DETECT_0        ("TRUE"),
         .DEC_VALID_COMMA_ONLY_0     ("FALSE"),
         .MCOMMA_10B_VALUE_0         (10'b1010000011),
         .MCOMMA_DETECT_0            ("TRUE"),
         .PCOMMA_10B_VALUE_0         (10'b0101111100),
         .PCOMMA_DETECT_0            ("TRUE"),
         .RX_SLIDE_MODE_0            ("PCS"),
         .ALIGN_COMMA_WORD_1         (2),
         .COMMA_10B_ENABLE_1         (10'b1111111111),
         .COMMA_DOUBLE_1             ("FALSE"),
         .DEC_MCOMMA_DETECT_1        ("TRUE"),
         .DEC_PCOMMA_DETECT_1        ("TRUE"),
         .DEC_VALID_COMMA_ONLY_1     ("FALSE"),
         .MCOMMA_10B_VALUE_1         (10'b1010000011),
         .MCOMMA_DETECT_1            ("TRUE"),
         .PCOMMA_10B_VALUE_1         (10'b0101111100),
         .PCOMMA_DETECT_1            ("TRUE"),
         .RX_SLIDE_MODE_1            ("PCS"),

         //------------------- RX Loss-of-sync State Machine -------------------  
         .RX_LOSS_OF_SYNC_FSM_0      ("FALSE"),
         .RX_LOS_INVALID_INCR_0      (8),
         .RX_LOS_THRESHOLD_0         (128),
         .RX_LOSS_OF_SYNC_FSM_1      ("FALSE"),
         .RX_LOS_INVALID_INCR_1      (8),
         .RX_LOS_THRESHOLD_1         (128),

         //------------ RX Elastic Buffer and Phase alignment ports ------------   
         .RX_BUFFER_USE_0            ("TRUE"),
         .RX_XCLK_SEL_0              ("RXREC"),
         .RX_BUFFER_USE_1            ("TRUE"),
         .RX_XCLK_SEL_1              ("RXREC"),

         //--------------------- Clock Correction Attributes -------------------   
         .CLK_CORRECT_USE_0          ("TRUE"),
         .CLK_COR_ADJ_LEN_0          (2),
         .CLK_COR_DET_LEN_0          (2),
         .CLK_COR_INSERT_IDLE_FLAG_0 ("FALSE"),
         .CLK_COR_KEEP_IDLE_0        ("FALSE"),
         .CLK_COR_MAX_LAT_0          (18),
         .CLK_COR_MIN_LAT_0          (16),
         .CLK_COR_PRECEDENCE_0       ("TRUE"),
         .CLK_COR_REPEAT_WAIT_0      (0),
         .CLK_COR_SEQ_1_1_0          (10'b0111110111),
         .CLK_COR_SEQ_1_2_0          (10'b0111110111),
         .CLK_COR_SEQ_1_3_0          (10'b0000000000),
         .CLK_COR_SEQ_1_4_0          (10'b0000000000),
         .CLK_COR_SEQ_1_ENABLE_0     (4'b0011),
         .CLK_COR_SEQ_2_1_0          (10'b0000000000),
         .CLK_COR_SEQ_2_2_0          (10'b0000000000),
         .CLK_COR_SEQ_2_3_0          (10'b0000000000),
         .CLK_COR_SEQ_2_4_0          (10'b0000000000),
         .CLK_COR_SEQ_2_ENABLE_0     (4'b0000),
         .CLK_COR_SEQ_2_USE_0        ("FALSE"),
         .RX_DECODE_SEQ_MATCH_0      ("TRUE"),
         .CLK_CORRECT_USE_1          ("TRUE"),
         .CLK_COR_ADJ_LEN_1          (2),
         .CLK_COR_DET_LEN_1          (2),
         .CLK_COR_INSERT_IDLE_FLAG_1 ("FALSE"),
         .CLK_COR_KEEP_IDLE_1        ("FALSE"),
         .CLK_COR_MAX_LAT_1          (18),
         .CLK_COR_MIN_LAT_1          (16),
         .CLK_COR_PRECEDENCE_1       ("TRUE"),
         .CLK_COR_REPEAT_WAIT_1      (0),
         .CLK_COR_SEQ_1_1_1          (10'b0111110111),
         .CLK_COR_SEQ_1_2_1          (10'b0111110111),
         .CLK_COR_SEQ_1_3_1          (10'b0000000000),
         .CLK_COR_SEQ_1_4_1          (10'b0000000000),
         .CLK_COR_SEQ_1_ENABLE_1     (4'b0011),
         .CLK_COR_SEQ_2_1_1          (10'b0000000000),
         .CLK_COR_SEQ_2_2_1          (10'b0000000000),
         .CLK_COR_SEQ_2_3_1          (10'b0000000000),
         .CLK_COR_SEQ_2_4_1          (10'b0000000000),
         .CLK_COR_SEQ_2_ENABLE_1     (4'b0000),
         .CLK_COR_SEQ_2_USE_1        ("FALSE"),
         .RX_DECODE_SEQ_MATCH_1      ("TRUE"),

         //-------------------- Channel Bonding Attributes ---------------------   
         .CHAN_BOND_1_MAX_SKEW_0     (7),
         .CHAN_BOND_2_MAX_SKEW_0     (7),
         .CHAN_BOND_LEVEL_0          (3'h0),
         .CHAN_BOND_MODE_0           ("OFF"),
         .CHAN_BOND_SEQ_1_1_0        (10'b0101111100),
         .CHAN_BOND_SEQ_1_2_0        (10'b0000000000),
         .CHAN_BOND_SEQ_1_3_0        (10'b0000000000),
         .CHAN_BOND_SEQ_1_4_0        (10'b0000000000),
         .CHAN_BOND_SEQ_1_ENABLE_0   (4'b0001),
         .CHAN_BOND_SEQ_2_1_0        (10'b0000000000),
         .CHAN_BOND_SEQ_2_2_0        (10'b0000000000),
         .CHAN_BOND_SEQ_2_3_0        (10'b0000000000),
         .CHAN_BOND_SEQ_2_4_0        (10'b0000000000),
         .CHAN_BOND_SEQ_2_ENABLE_0   (4'b0000),
         .CHAN_BOND_SEQ_2_USE_0      ("FALSE"),  
         .CHAN_BOND_SEQ_LEN_0        (1),
         .PCI_EXPRESS_MODE_0         ("FALSE"),     
         .CHAN_BOND_1_MAX_SKEW_1     (7),
         .CHAN_BOND_2_MAX_SKEW_1     (7),
         .CHAN_BOND_LEVEL_1          (3'h0),
         .CHAN_BOND_MODE_1           (CHAN_BOND_MODE_1),
	 .CHAN_BOND_SEQ_1_1_1        (10'b0101111100),
	 .CHAN_BOND_SEQ_1_2_1        (10'b0000000000),
	 .CHAN_BOND_SEQ_1_3_1        (10'b0000000000),
	 .CHAN_BOND_SEQ_1_4_1        (10'b0000000000),
	 .CHAN_BOND_SEQ_1_ENABLE_1   (4'b0001),
	 .CHAN_BOND_SEQ_2_1_1        (10'b0000000000),
	 .CHAN_BOND_SEQ_2_2_1        (10'b0000000000),
	 .CHAN_BOND_SEQ_2_3_1        (10'b0000000000),
	 .CHAN_BOND_SEQ_2_4_1        (10'b0000000000),
	 .CHAN_BOND_SEQ_2_ENABLE_1   (4'b0000),
	 .CHAN_BOND_SEQ_2_USE_1      ("FALSE"),  
	 .CHAN_BOND_SEQ_LEN_1        (1),
         .PCI_EXPRESS_MODE_1         ("FALSE"),

         //---------------- RX Attributes for PCI Express/SATA ---------------
         .RX_STATUS_FMT_0            ("PCIE"),
         .SATA_BURST_VAL_0           (3'b100),
         .SATA_IDLE_VAL_0            (3'b100),
         .SATA_MAX_BURST_0           (7),
         .SATA_MAX_INIT_0            (22),
         .SATA_MAX_WAKE_0            (7),
         .SATA_MIN_BURST_0           (4),
         .SATA_MIN_INIT_0            (12),
         .SATA_MIN_WAKE_0            (4),
         .TRANS_TIME_FROM_P2_0       (16'h0060),
         .TRANS_TIME_NON_P2_0        (16'h0025),
         .TRANS_TIME_TO_P2_0         (16'h0100),
         .RX_STATUS_FMT_1            ("PCIE"),
         .SATA_BURST_VAL_1           (3'b100),
         .SATA_IDLE_VAL_1            (3'b100),
         .SATA_MAX_BURST_1           (7),
         .SATA_MAX_INIT_1            (22),
         .SATA_MAX_WAKE_1            (7),
         .SATA_MIN_BURST_1           (4),
         .SATA_MIN_INIT_1            (12),
         .SATA_MIN_WAKE_1            (4),
         .TRANS_TIME_FROM_P2_1       (16'h0060),
         .TRANS_TIME_NON_P2_1        (16'h0025),
         .TRANS_TIME_TO_P2_1         (16'h0100)         
     ) 
GTP_DUAL_INST (
         //---------------------- Loopback and Powerdown Ports ----------------------
         .LOOPBACK0                  (3'b000),
         .LOOPBACK1                  (LOOPBACK_IN),
         .RXPOWERDOWN0               (tied_to_ground_vec_i[1:0]),
         .RXPOWERDOWN1               ({POWERDOWN_IN,POWERDOWN_IN}),
         .TXPOWERDOWN0               (tied_to_ground_vec_i[1:0]),
         .TXPOWERDOWN1               ({POWERDOWN_IN,POWERDOWN_IN}),

         //--------------------- Receive Ports - 8b10b Decoder ----------------------
         .RXCHARISCOMMA0             (),
         .RXCHARISCOMMA1             (RXCHARISCOMMA_OUT ),
         .RXCHARISK0                 (),
         .RXCHARISK1                 (RXCHARISK_OUT),
         .RXDEC8B10BUSE0             (tied_to_vcc_i),
         .RXDEC8B10BUSE1             (tied_to_vcc_i),
         .RXDISPERR0                 (),
         .RXDISPERR1                 (RXDISPERR_OUT),
         .RXNOTINTABLE0              (),
         .RXNOTINTABLE1              (RXNOTINTABLE_OUT),
         .RXRUNDISP0                 ( ),
         .RXRUNDISP1                 ( ),

         //----------------- Receive Ports - Channel Bonding Ports ------------------
         .RXCHANBONDSEQ0             ( ),
         .RXCHANBONDSEQ1             ( ),
         .RXCHBONDI0                 (tied_to_ground_vec_i[2:0]),
         .RXCHBONDI1                 (chbondi),
         .RXCHBONDO0                 ( ),
         .RXCHBONDO1                 (chbondo ),
         .RXENCHANSYNC0              (tied_to_ground_i),
         .RXENCHANSYNC1              (ENCHANSYNC_IN),

         //----------------- Receive Ports - Clock Correction Ports -----------------
         .RXCLKCORCNT0               (),
         .RXCLKCORCNT1               (),

         //------------- Receive Ports - Comma Detection and Alignment --------------
         .RXBYTEISALIGNED0           ( ),
         .RXBYTEISALIGNED1           ( ),
         .RXBYTEREALIGN0             ( ),
         .RXBYTEREALIGN1             (RXREALIGN_OUT),
         .RXCOMMADET0                ( ),
         .RXCOMMADET1                ( ),
         .RXCOMMADETUSE0             (tied_to_vcc_i),
         .RXCOMMADETUSE1             (tied_to_vcc_i),
         .RXENMCOMMAALIGN0           (tied_to_ground_i),
         .RXENMCOMMAALIGN1           (ENMCOMMAALIGN_IN),
         .RXENPCOMMAALIGN0           (tied_to_ground_i),
         .RXENPCOMMAALIGN1           (ENPCOMMAALIGN_IN),
         .RXSLIDE0                   (tied_to_ground_i),
         .RXSLIDE1                   (tied_to_ground_i),

         //--------------------- Receive Ports - PRBS Detection ---------------------
         .PRBSCNTRESET0              (tied_to_ground_i),
         .PRBSCNTRESET1              (tied_to_ground_i),
         .RXENPRBSTST0               (tied_to_ground_vec_i[1:0]),
         .RXENPRBSTST1               (tied_to_ground_vec_i[1:0]),
         .RXPRBSERR0                 ( ),
         .RXPRBSERR1                 ( ),

         //----------------- Receive Ports - RX Data Path interface -----------------
         .RXDATA0                    (),
         .RXDATA1                    (RXDATA_OUT),
         .RXDATAWIDTH0               (tied_to_vcc_i),
         .RXDATAWIDTH1               (tied_to_vcc_i),
         .RXRECCLK0                  (),
         .RXRECCLK1                  (RXRECCLK1_OUT),
         .RXRESET0                   (tied_to_ground_i),
         .RXRESET1                   (RXRESET_IN),
         .RXUSRCLK0                  (tied_to_ground_i),
         .RXUSRCLK1                  (RXUSRCLK_IN),
         .RXUSRCLK20                 (tied_to_ground_i),
         .RXUSRCLK21                 (RXUSRCLK2_IN),

         //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
         .RXCDRRESET0                (tied_to_ground_i),
         .RXCDRRESET1                (tied_to_ground_i),
         .RXELECIDLE0                (rxelecidle0_i),
         .RXELECIDLE1                (rxelecidle1_i),
         .RXELECIDLERESET0           (rxelecidlereset0_i),
         .RXELECIDLERESET1           (rxelecidlereset1_i),
         .RXENEQB0                   (tied_to_vcc_i),
         .RXENEQB1                   (tied_to_vcc_i),
         .RXEQMIX0                   (tied_to_ground_vec_i[1:0]),
         .RXEQMIX1                   (tied_to_ground_vec_i[1:0]),
         .RXEQPOLE0                  (tied_to_ground_vec_i[3:0]),
         .RXEQPOLE1                  (tied_to_ground_vec_i[3:0]),
         .RXN0                       (),
         .RXN1                       (RX1N_IN),
         .RXP0                       (),
         .RXP1                       (RX1P_IN),

         //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
         .RXBUFRESET0                (tied_to_ground_i),
         .RXBUFRESET1                (tied_to_ground_i),
         .RXBUFSTATUS0               ( ),
         .RXBUFSTATUS1               ({RXBUFERR_OUT,open_rxbufstatus_i} ),
         .RXCHANISALIGNED0           (),
         .RXCHANISALIGNED1           (CHBONDDONE_OUT ),
         .RXCHANREALIGN0             ( ),
         .RXCHANREALIGN1             ( ),
         .RXPMASETPHASE0             (tied_to_ground_i),
         .RXPMASETPHASE1             (tied_to_ground_i),
         .RXSTATUS0                  ( ),
         .RXSTATUS1                  ( ),

         //------------- Receive Ports - RX Loss-of-sync State Machine --------------
         .RXLOSSOFSYNC0              ( ),
         .RXLOSSOFSYNC1              ( ),

         //-------------------- Receive Ports - RX Oversampling ---------------------
         .RXENSAMPLEALIGN0           (tied_to_ground_i),
         .RXENSAMPLEALIGN1           (tied_to_ground_i),
         .RXOVERSAMPLEERR0           ( ),
         .RXOVERSAMPLEERR1           ( ),

         //------------ Receive Ports - RX Pipe Control for PCI Express -------------
         .PHYSTATUS0                 ( ),
         .PHYSTATUS1                 ( ),
         .RXVALID0                   ( ),
         .RXVALID1                   ( ),

         //--------------- Receive Ports - RX Polarity Control Ports ----------------
         .RXPOLARITY0                (tied_to_ground_i),
         .RXPOLARITY1                (RXPOLARITY_IN),

         //----------- Shared Ports - Dynamic Reconfiguration Port (DRP) ------------
         .DADDR                      (tied_to_ground_vec_i[6:0]),
         .DCLK                       (tied_to_ground_i),
         .DEN                        (tied_to_ground_i),
         .DI                         (tied_to_ground_vec_i[15:0]),
         .DO                         ( ),
         .DRDY                       ( ),
         .DWE                        (tied_to_ground_i),

         //------------------- Shared Ports - Tile and PLL Ports --------------------
         .CLKIN                      (REFCLK),
         .GTPRESET                   (GTPRESET_IN),
         .GTPTEST                    (tied_to_ground_vec_i[3:0]),
         .INTDATAWIDTH               (tied_to_vcc_i),
         .PLLLKDET                   (plllkdet_i),
         .PLLLKDETEN                 (tied_to_vcc_i),
         .PLLPOWERDOWN               (POWERDOWN_IN),
         .REFCLKOUT                  (),
         .REFCLKPWRDNB               (tied_to_vcc_i),
         .RESETDONE0                 (resetdone0_i),
         .RESETDONE1                 (resetdone1_i),
         .RXENELECIDLERESETB         (rxenelecidleresetb_i),
         .TXENPMAPHASEALIGN          (tied_to_ground_i),
         .TXPMASETPHASE              (tied_to_ground_i),

         //-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
         .TXBYPASS8B10B0             (tied_to_ground_vec_i[1:0]),
         .TXBYPASS8B10B1             (tied_to_ground_vec_i[1:0]),
         .TXCHARDISPMODE0            (tied_to_ground_vec_i[1:0]),
         .TXCHARDISPMODE1            (tied_to_ground_vec_i[1:0]),
         .TXCHARDISPVAL0             (tied_to_ground_vec_i[1:0]),
         .TXCHARDISPVAL1             (tied_to_ground_vec_i[1:0]),
         .TXCHARISK0                 (tied_to_ground_vec_i[1:0]),
         .TXCHARISK1                 (TXCHARISK_IN),
         
         .TXENC8B10BUSE0             (tied_to_vcc_i),
         .TXENC8B10BUSE1             (tied_to_vcc_i),
         .TXKERR0                    ( ),
         .TXKERR1                    ( ),
         .TXRUNDISP0                 ( ),
         .TXRUNDISP1                 ( ),

         //----------- Transmit Ports - TX Buffering and Phase Alignment ------------
         .TXBUFSTATUS0               ( ),
         .TXBUFSTATUS1               ({TXBUFERR_OUT, open_txbufstatus_i}),

         //---------------- Transmit Ports - TX Data Path interface -----------------
         .TXDATA0                    (tied_to_ground_vec_i[15:0]),         
         .TXDATA1                    (TXDATA_IN),
         
         .TXDATAWIDTH0               (tied_to_vcc_i),
         .TXDATAWIDTH1               (tied_to_vcc_i),
         .TXOUTCLK0                  (),
         .TXOUTCLK1                  (TXOUTCLK1_OUT),
         .TXRESET0                   (tied_to_ground_i),
         .TXRESET1                   (TXRESET_IN),
         .TXUSRCLK0                  (tied_to_ground_i),
         .TXUSRCLK1                  (TXUSRCLK_IN ),
         .TXUSRCLK20                 (tied_to_ground_i),
         .TXUSRCLK21                 (TXUSRCLK2_IN),
         //------------- Transmit Ports - TX Driver and OOB signalling --------------
         .TXBUFDIFFCTRL0             (3'b000),
         .TXBUFDIFFCTRL1             (3'b000),
         .TXDIFFCTRL0                (3'b000),
         .TXDIFFCTRL1                (3'b000),
         .TXINHIBIT0                 (tied_to_ground_i),
         .TXINHIBIT1                 (tied_to_ground_i),
         .TXN0                       (),
         .TXN1                       (TX1N_OUT),
         .TXP0                       (),
         .TXP1                       (TX1P_OUT),
         .TXPREEMPHASIS0             (3'b000),
         .TXPREEMPHASIS1             (3'b000),

         //------------------- Transmit Ports - TX PRBS Generator -------------------
         .TXENPRBSTST0               (tied_to_ground_vec_i[1:0]),
         .TXENPRBSTST1               (tied_to_ground_vec_i[1:0]),

         //------------------ Transmit Ports - TX Polarity Control ------------------
         .TXPOLARITY0                (tied_to_ground_i),
         .TXPOLARITY1                (tied_to_ground_i),

         //--------------- Transmit Ports - TX Ports for PCI Express ----------------
         .TXDETECTRX0                (tied_to_ground_i),
         .TXDETECTRX1                (tied_to_ground_i),
         .TXELECIDLE0                (tied_to_ground_i),
         .TXELECIDLE1                (tied_to_ground_i),

         //------------------- Transmit Ports - TX Ports for SATA -------------------
         .TXCOMSTART0                (tied_to_ground_i),
         .TXCOMSTART1                (tied_to_ground_i),
         .TXCOMTYPE0                 (tied_to_ground_i),
         .TXCOMTYPE1                 (tied_to_ground_i)
  );

 
endmodule


